version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.0
    working_directory: /go/src/github.com/otknoy/dmm-search-api
    steps:
      - checkout
      - run: go test -v -race -cover ./...
      - run: go build ./
